# coding: utf-8

"""
    DevInbox API

    API for creating temporary mailboxes and managing messages for testing purposes

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_get_last_message(self) -> None:
        """Test case for get_last_message

        Get last message from mailbox
        """
        pass

    def test_get_last_message_with_template(self) -> None:
        """Test case for get_last_message_with_template

        Get last message with template parsing
        """
        pass

    def test_get_message_by_id(self) -> None:
        """Test case for get_message_by_id

        Get a specific message by ID
        """
        pass

    def test_get_message_count(self) -> None:
        """Test case for get_message_count

        Get message count
        """
        pass

    def test_get_messages(self) -> None:
        """Test case for get_messages

        Get messages from a mailbox
        """
        pass

    def test_get_single_message(self) -> None:
        """Test case for get_single_message

        Get single message from mailbox
        """
        pass

    def test_get_single_message_with_template(self) -> None:
        """Test case for get_single_message_with_template

        Get single message with template parsing
        """
        pass


if __name__ == '__main__':
    unittest.main()
