# coding: utf-8

"""
    DevInbox API

    API for creating temporary mailboxes and managing messages for testing purposes

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.api.mailboxes_api import MailboxesApi


class TestMailboxesApi(unittest.TestCase):
    """MailboxesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailboxesApi()

    def tearDown(self) -> None:
        pass

    def test_create_mailbox(self) -> None:
        """Test case for create_mailbox

        Create a new mailbox
        """
        pass


if __name__ == '__main__':
    unittest.main()
