# coding: utf-8

"""
    DevInbox.ApiService | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.models.get_messages_skip_parameter import GetMessagesSkipParameter

class TestGetMessagesSkipParameter(unittest.TestCase):
    """GetMessagesSkipParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMessagesSkipParameter:
        """Test GetMessagesSkipParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMessagesSkipParameter`
        """
        model = GetMessagesSkipParameter()
        if include_optional:
            return GetMessagesSkipParameter(
            )
        else:
            return GetMessagesSkipParameter(
        )
        """

    def testGetMessagesSkipParameter(self):
        """Test GetMessagesSkipParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
