# coding: utf-8

"""
    DevInbox.ApiService | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.models.messages_view_model_count import MessagesViewModelCount

class TestMessagesViewModelCount(unittest.TestCase):
    """MessagesViewModelCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagesViewModelCount:
        """Test MessagesViewModelCount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagesViewModelCount`
        """
        model = MessagesViewModelCount()
        if include_optional:
            return MessagesViewModelCount(
            )
        else:
            return MessagesViewModelCount(
        )
        """

    def testMessagesViewModelCount(self):
        """Test MessagesViewModelCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
