# coding: utf-8

"""
    DevInbox API

    API for managing test mailboxes and messages in DevInbox (OpenAPI 3.0)

    The version of the OpenAPI document: v1
    Contact: support@devinbox.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.models.mailbox_view_model import MailboxViewModel

class TestMailboxViewModel(unittest.TestCase):
    """MailboxViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailboxViewModel:
        """Test MailboxViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailboxViewModel`
        """
        model = MailboxViewModel()
        if include_optional:
            return MailboxViewModel(
                key = '',
                password = ''
            )
        else:
            return MailboxViewModel(
        )
        """

    def testMailboxViewModel(self):
        """Test MailboxViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
