# coding: utf-8

# flake8: noqa
"""
    DevInbox API

    API for creating temporary mailboxes and managing messages for testing purposes

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from devinbox_client.models.mailbox_create_model import MailboxCreateModel
    from devinbox_client.models.mailbox_view_model import MailboxViewModel
    from devinbox_client.models.message_count_result import MessageCountResult
    from devinbox_client.models.message_parsed_view_model import MessageParsedViewModel
    from devinbox_client.models.message_view_model import MessageViewModel
    from devinbox_client.models.messages_view_model import MessagesViewModel
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from devinbox_client.models.mailbox_create_model import MailboxCreateModel
from devinbox_client.models.mailbox_view_model import MailboxViewModel
from devinbox_client.models.message_count_result import MessageCountResult
from devinbox_client.models.message_parsed_view_model import MessageParsedViewModel
from devinbox_client.models.message_view_model import MessageViewModel
from devinbox_client.models.messages_view_model import MessagesViewModel

""",
            name=__name__,
            doc=__doc__,
        )
    )
