# coding: utf-8

# flake8: noqa
"""
    DevInbox.ApiService | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from devinbox_client.models.get_messages_skip_parameter import GetMessagesSkipParameter
    from devinbox_client.models.mailbox_create_model import MailboxCreateModel
    from devinbox_client.models.mailbox_view_model import MailboxViewModel
    from devinbox_client.models.message_count_result import MessageCountResult
    from devinbox_client.models.message_count_result_count import MessageCountResultCount
    from devinbox_client.models.message_parsed_view_model import MessageParsedViewModel
    from devinbox_client.models.message_view_model import MessageViewModel
    from devinbox_client.models.messages_view_model import MessagesViewModel
    from devinbox_client.models.messages_view_model_count import MessagesViewModelCount
    from devinbox_client.models.problem_details import ProblemDetails
    from devinbox_client.models.problem_details_status import ProblemDetailsStatus
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from devinbox_client.models.get_messages_skip_parameter import GetMessagesSkipParameter
from devinbox_client.models.mailbox_create_model import MailboxCreateModel
from devinbox_client.models.mailbox_view_model import MailboxViewModel
from devinbox_client.models.message_count_result import MessageCountResult
from devinbox_client.models.message_count_result_count import MessageCountResultCount
from devinbox_client.models.message_parsed_view_model import MessageParsedViewModel
from devinbox_client.models.message_view_model import MessageViewModel
from devinbox_client.models.messages_view_model import MessagesViewModel
from devinbox_client.models.messages_view_model_count import MessagesViewModelCount
from devinbox_client.models.problem_details import ProblemDetails
from devinbox_client.models.problem_details_status import ProblemDetailsStatus

""",
            name=__name__,
            doc=__doc__,
        )
    )
