# coding: utf-8

# flake8: noqa

"""
    DevInbox.ApiService | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "MailboxesApi",
    "MessagesApi",
    "StatusApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "GetMessagesSkipParameter",
    "MailboxCreateModel",
    "MailboxViewModel",
    "MessageCountResult",
    "MessageCountResultCount",
    "MessageParsedViewModel",
    "MessageViewModel",
    "MessagesViewModel",
    "MessagesViewModelCount",
    "ProblemDetails",
    "ProblemDetailsStatus",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from devinbox_client.api.mailboxes_api import MailboxesApi as MailboxesApi
    from devinbox_client.api.messages_api import MessagesApi as MessagesApi
    from devinbox_client.api.status_api import StatusApi as StatusApi
    
    # import ApiClient
    from devinbox_client.api_response import ApiResponse as ApiResponse
    from devinbox_client.api_client import ApiClient as ApiClient
    from devinbox_client.configuration import Configuration as Configuration
    from devinbox_client.exceptions import OpenApiException as OpenApiException
    from devinbox_client.exceptions import ApiTypeError as ApiTypeError
    from devinbox_client.exceptions import ApiValueError as ApiValueError
    from devinbox_client.exceptions import ApiKeyError as ApiKeyError
    from devinbox_client.exceptions import ApiAttributeError as ApiAttributeError
    from devinbox_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from devinbox_client.models.get_messages_skip_parameter import GetMessagesSkipParameter as GetMessagesSkipParameter
    from devinbox_client.models.mailbox_create_model import MailboxCreateModel as MailboxCreateModel
    from devinbox_client.models.mailbox_view_model import MailboxViewModel as MailboxViewModel
    from devinbox_client.models.message_count_result import MessageCountResult as MessageCountResult
    from devinbox_client.models.message_count_result_count import MessageCountResultCount as MessageCountResultCount
    from devinbox_client.models.message_parsed_view_model import MessageParsedViewModel as MessageParsedViewModel
    from devinbox_client.models.message_view_model import MessageViewModel as MessageViewModel
    from devinbox_client.models.messages_view_model import MessagesViewModel as MessagesViewModel
    from devinbox_client.models.messages_view_model_count import MessagesViewModelCount as MessagesViewModelCount
    from devinbox_client.models.problem_details import ProblemDetails as ProblemDetails
    from devinbox_client.models.problem_details_status import ProblemDetailsStatus as ProblemDetailsStatus
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from devinbox_client.api.mailboxes_api import MailboxesApi as MailboxesApi
from devinbox_client.api.messages_api import MessagesApi as MessagesApi
from devinbox_client.api.status_api import StatusApi as StatusApi

# import ApiClient
from devinbox_client.api_response import ApiResponse as ApiResponse
from devinbox_client.api_client import ApiClient as ApiClient
from devinbox_client.configuration import Configuration as Configuration
from devinbox_client.exceptions import OpenApiException as OpenApiException
from devinbox_client.exceptions import ApiTypeError as ApiTypeError
from devinbox_client.exceptions import ApiValueError as ApiValueError
from devinbox_client.exceptions import ApiKeyError as ApiKeyError
from devinbox_client.exceptions import ApiAttributeError as ApiAttributeError
from devinbox_client.exceptions import ApiException as ApiException

# import models into sdk package
from devinbox_client.models.get_messages_skip_parameter import GetMessagesSkipParameter as GetMessagesSkipParameter
from devinbox_client.models.mailbox_create_model import MailboxCreateModel as MailboxCreateModel
from devinbox_client.models.mailbox_view_model import MailboxViewModel as MailboxViewModel
from devinbox_client.models.message_count_result import MessageCountResult as MessageCountResult
from devinbox_client.models.message_count_result_count import MessageCountResultCount as MessageCountResultCount
from devinbox_client.models.message_parsed_view_model import MessageParsedViewModel as MessageParsedViewModel
from devinbox_client.models.message_view_model import MessageViewModel as MessageViewModel
from devinbox_client.models.messages_view_model import MessagesViewModel as MessagesViewModel
from devinbox_client.models.messages_view_model_count import MessagesViewModelCount as MessagesViewModelCount
from devinbox_client.models.problem_details import ProblemDetails as ProblemDetails
from devinbox_client.models.problem_details_status import ProblemDetailsStatus as ProblemDetailsStatus

""",
            name=__name__,
            doc=__doc__,
        )
    )
