# coding: utf-8

"""
    DevInbox API

    API for managing test mailboxes and messages in DevInbox (OpenAPI 3.0)

    The version of the OpenAPI document: v1
    Contact: support@devinbox.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.models.message_view_model import MessageViewModel

class TestMessageViewModel(unittest.TestCase):
    """MessageViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageViewModel:
        """Test MessageViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageViewModel`
        """
        model = MessageViewModel()
        if include_optional:
            return MessageViewModel(
                unique_id = '',
                var_from = [
                    ''
                    ],
                to = [
                    ''
                    ],
                cc = [
                    ''
                    ],
                bcc = [
                    ''
                    ],
                subject = '',
                body = '',
                is_html = True,
                received = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MessageViewModel(
        )
        """

    def testMessageViewModel(self):
        """Test MessageViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
