# coding: utf-8

"""
    DevInbox API

    API for managing test mailboxes and messages in DevInbox (OpenAPI 3.0)

    The version of the OpenAPI document: v1
    Contact: support@devinbox.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devinbox_client.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_get_last_message(self) -> None:
        """Test case for get_last_message

        Get the last message from a mailbox
        """
        pass

    def test_get_last_message_with_template(self) -> None:
        """Test case for get_last_message_with_template

        Get the last message with template parsing
        """
        pass

    def test_get_message_by_id(self) -> None:
        """Test case for get_message_by_id

        Get a specific message by ID
        """
        pass

    def test_get_message_count(self) -> None:
        """Test case for get_message_count

        Get message count for a mailbox
        """
        pass

    def test_get_messages(self) -> None:
        """Test case for get_messages

        Get messages from a mailbox
        """
        pass

    def test_get_single_message(self) -> None:
        """Test case for get_single_message

        Get single message from a mailbox
        """
        pass

    def test_get_single_message_with_template(self) -> None:
        """Test case for get_single_message_with_template

        Get single message with template parsing
        """
        pass


if __name__ == '__main__':
    unittest.main()
